### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by etiennecallies** [ramustha/unix-timestamp#19]
Hi! Awesome plugin. Would it be possible to support python files ?
Example:
```python
o = Object(
    start_time=1699102800,
    end_time=1699110000,
)
```

**Comment by ramustha** [comment]
sure @etiennecallies it possible to support pythons in the next release v5.1.0

**Comment by etiennecallies** [comment]
Hi @ramustha! Many thanks! I could not wait to try it, but it does not seem to work...

I'm using PyCharm CE (on latest version)
![Screenshot 2023-11-27 at 09 55 03](https://github.com/ramustha/unix-timestamp/assets/7634514/0dcc1aaa-743d-44a7-9322-82e3cf56fd18)

I installed and activated version 5.1.0 (restarted the IDE, tried to uninstall/re-install the plugin...).

I expected to see some human-readable time in this example, on code and output.
![Screenshot 2023-11-27 at 09 57 06](https://github.com/ramustha/unix-timestamp/assets/7634514/c51f85e5-6462-4dd5-9eb4-e98a7a43b021)

Did I miss sth?

**Comment by ramustha** [comment]
hi @etiennecallies, thanks for your quick feedback, I realized for now this plugin only targets intellij CE/UE, you can try it in intellij CE by installing a separate python plugin, I'm afraid you will have to wait longer for the next release for intellij products like pyCharm and others other
