### ISSUE TITLE
Latest update is less user-friendly for timestamp with decimals.

### ISSUE THREAD

**Issue by PieterDr** [ramustha/unix-timestamp#25]
The inlays used to always be at the end of the line. Since the latest update they appear inline, right next to the timestamp. For timestamps with decimal numbers, they appear before the decimal point which makes them a bit invasive.

Before:
![image](https://github.com/ramustha/unix-timestamp/assets/8881051/3133ca0d-34c1-4b1e-a64f-4349de196a84)

After:
![image](https://github.com/ramustha/unix-timestamp/assets/8881051/d42a353e-8863-499c-9ff9-8b61f5f255dc)

**Comment by ramustha** [comment]
Published [Unix Timestamp Converter 6.0.2](https://plugins.jetbrains.com/plugin/19499-unix-timestamp-converter/versions/stable/465382?noRedirect=true)
